spring:
  application:
    name: glowdrop
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/glowdrop}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

server:
  port: ${PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: health,info
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info
